# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: lempira@gmail.com
author_name: David Rojas
contract_name: caller_contract
deployment_language: typescript
preset_name: production
project_name: utils-ts-371

